
spring:
  application:
    name: restaurant_reservation
  datasource:
    url: jdbc:mysql://localhost:3308/zini_shop?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: zini_reservation_user
    password: kukugi251001
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  batch:
    jdbc:
      initialize-schema: always

